site_name: ac-library-mojo Docs
docs_dir: docs
site_dir: site
site_url: https://shogo314.github.io/page-test/
repo_url: https://github.com/shogo314/page-test

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - version-selector

extra:
  version:
    provider: mike

nav:
  - ホーム: index.md
  - モジュール:
    - convolution:
      - modules/convolution/index.md

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          name: 日本語
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            ホーム: Home
            モジュール: Modules

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex
  - admonition:
  - pymdownx.superfences:
  - pymdownx.highlight:
  - pymdownx.inlinehilite:
  - pymdownx.details:
  - pymdownx.emoji:
  - codehilite:
      guess_lang: false
